# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# Motion scaling factors
default_velocity_scaling_factor: 0.5  # Increased speed (adjust as needed)
default_acceleration_scaling_factor: 0.3  # Added acceleration scaling

# Specific joint properties
joint_limits:
  base_chassis_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true  # Now limiting acceleration
    max_acceleration: 30.0  # Adjust based on your simulation needs
  chassis_boom_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 30.0
  boom_stick_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 30.0
  stick_bucket_joint:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: true
    max_acceleration: 30.0
