# Limits for the Pilz planner
cartesian_limits:
  max_trans_vel: 1.0    # Maximum translational velocity (m/s)
  max_trans_acc: 2.25   # Maximum translational acceleration (m/s²)
  max_trans_dec: 5.0    # Ensure this is a positive value if needed
  max_rot_vel: 1.57     # Maximum rotational velocity (rad/s)
